import { useState, useEffect } from "react";
import { Lock, Wand2, Download, FileText } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { listDprs, generateRfp, listRfps } from "../api";
import { useToast } from "../components/Toast";

export default function RfpManagement() {
  const [dprs, setDprs] = useState([]);
  const [rfps, setRfps] = useState([]);
  const [selectedDpr, setSelectedDpr] = useState("");
  const [currentRfp, setCurrentRfp] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [loading, setLoading] = useState(true);
  const toast = useToast();

  useEffect(() => {
    (async () => {
      try {
        const [dprData, rfpData] = await Promise.all([listDprs(), listRfps()]);
        setDprs(dprData.filter((d) => d.status === "APPROVED"));
        setRfps(rfpData);
      } catch (err) {
        toast.error(err.message);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const handleGenerate = async () => {
    if (!selectedDpr) return toast.error("Select an approved DPR first");
    setGenerating(true);
    setCurrentRfp(null);
    try {
      const rfp = await generateRfp(selectedDpr);
      setCurrentRfp(rfp);
      setRfps((prev) => [rfp, ...prev]);
      toast.success(`RFP #${rfp.id} generated`);
    } catch (err) {
      toast.error(err.message);
    } finally {
      setGenerating(false);
    }
  };

  // Show existing RFP for selected DPR
  useEffect(() => {
    if (selectedDpr) {
      const existing = rfps.find((r) => r.dpr_id === parseInt(selectedDpr));
      setCurrentRfp(existing || null);
    }
  }, [selectedDpr, rfps]);

  const selectedDprObj = dprs.find((d) => d.id === parseInt(selectedDpr));

  const downloadRfpMd = (rfp) => {
    const blob = new Blob([rfp.generated_markdown], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `RFP-${rfp.id}-DPR-${rfp.dpr_id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadRfpPdf = (rfp, dprObj) => {
    const fmt = (v) => `₹${Number(v).toLocaleString("en-IN")}`;
    // Convert markdown headings/bold for display
    const mdToHtml = (md) =>
      md
        .replace(/^### (.+)$/gm, "<h3>$1</h3>")
        .replace(/^## (.+)$/gm, "<h2>$1</h2>")
        .replace(/^# (.+)$/gm, "<h1 class='md-h1'>$1</h1>")
        .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
        .replace(/^- (.+)$/gm, "<li>$1</li>")
        .replace(/(<li>.*<\/li>)/gs, "<ul>$1</ul>")
        .replace(/\n/g, "<br/>");
    const html = `
      <!DOCTYPE html><html><head><title>RFP #${rfp.id}</title>
      <style>
        body { font-family: Arial, sans-serif; max-width: 860px; margin: 40px auto; color: #1e293b; }
        h1 { color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 8px; }
        h2 { color: #1e40af; font-size: 1.1rem; margin-top: 1.5rem; }
        h3 { color: #334155; font-size: 1rem; }
        .md-h1 { color: #334155; font-size: 1.2rem; border-bottom: 1px solid #e2e8f0; }
        .finance-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 16px 0; }
        .finance-card { background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 12px; }
        .finance-card label { font-size: 0.75rem; color: #3b82f6; display: block; margin-bottom: 4px; }
        .finance-card strong { color: #1e40af; font-size: 1rem; }
        .content { line-height: 1.7; color: #374151; }
        ul { padding-left: 1.5rem; }
        li { margin: 4px 0; }
        footer { margin-top: 2rem; font-size: 0.75rem; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 8px; }
        @media print { body { margin: 20px; } }
      </style></head><body>
      <h1>Request for Proposal</h1>
      <p>Government of Uttarakhand &nbsp;|&nbsp; Budget Department</p>
      <p style="color:#64748b; margin-top:4px">RFP #${rfp.id} &nbsp;&bull;&nbsp; DPR #${rfp.dpr_id}${dprObj ? " &mdash; " + dprObj.title : ""}</p>
      <h2>Financial Summary</h2>
      <div class="finance-row">
        <div class="finance-card"><label>EMD (2%)</label><strong>${rfp.emd?.formatted || ""}</strong></div>
        <div class="finance-card"><label>Performance Guarantee (5%)</label><strong>${rfp.performance_guarantee?.formatted || ""}</strong></div>
        <div class="finance-card"><label>Liquidated Damages</label><strong>${rfp.liquidated_damages?.formatted || ""}</strong></div>
      </div>
      <h2>Tender Document</h2>
      <div class="content">${mdToHtml(rfp.generated_markdown)}</div>
      <footer>Generated by GovDraft Ecosystem · ${new Date().toLocaleString("en-IN")}</footer>
      </body></html>`;
    const win = window.open("", "_blank");
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 500);
  };

  return (
    <div className="page-container">
      <div className="page-header">
        <h1>RFP Management</h1>
        <p>Generate AI-powered Request for Proposals with deterministic financial calculations.</p>
      </div>

      <div className="glass-card" style={{ marginBottom: "1.5rem" }}>
        <div style={{ display: "flex", gap: "1rem", alignItems: "flex-end", flexWrap: "wrap" }}>
          <div className="form-group" style={{ flex: 1, minWidth: 200, marginBottom: 0 }}>
            <label>Select Approved DPR</label>
            <select className="form-control" value={selectedDpr} onChange={(e) => setSelectedDpr(e.target.value)}>
              <option value="">— choose a DPR —</option>
              {dprs.map((d) => (
                <option key={d.id} value={d.id}>
                  #{d.id} — {d.title} (₹{Number(d.project_cost).toLocaleString("en-IN")})
                </option>
              ))}
            </select>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}>
            <button
              className="btn btn-primary"
              onClick={handleGenerate}
              disabled={generating || !selectedDpr || !!currentRfp}
              title={currentRfp ? "An RFP has already been generated for this DPR" : ""}
            >
              {generating ? <span className="spinner" /> : <Wand2 size={16} />}
              {generating ? "Generating…" : "Generate Tender Clauses"}
            </button>
            {currentRfp && (
              <span style={{ fontSize: "0.75rem", color: "#f59e0b", display: "flex", alignItems: "center", gap: 4 }}>
                ⚠ RFP #{currentRfp.id} already exists for this DPR
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Financial Badges */}
      {currentRfp && (
        <div className="finance-badges">
          <div className="finance-badge">
            <Lock size={14} className="lock-icon" />
            <div>
              <div className="label">EMD (2%)</div>
              <div className="amount">{currentRfp.emd?.formatted}</div>
            </div>
          </div>
          <div className="finance-badge">
            <Lock size={14} className="lock-icon" />
            <div>
              <div className="label">Performance Guarantee (5%)</div>
              <div className="amount">{currentRfp.performance_guarantee?.formatted}</div>
            </div>
          </div>
          <div className="finance-badge">
            <Lock size={14} className="lock-icon" />
            <div>
              <div className="label">Liquidated Damages</div>
              <div className="amount">{currentRfp.liquidated_damages?.formatted}</div>
            </div>
          </div>
        </div>
      )}

      {/* Generated RFP Preview */}
      {generating && (
        <div className="glass-card">
          <div className="loading-overlay">
            <div className="spinner" />
            <span>Generating RFP with AI… (financial numbers are pre-calculated)</span>
          </div>
        </div>
      )}

      {currentRfp && !generating && (
        <div className="glass-card" style={{ marginTop: "1.5rem" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1rem", flexWrap: "wrap", gap: "0.5rem" }}>
            <h3 style={{ fontSize: "1rem", fontWeight: 600 }}>
              Generated RFP #{currentRfp.id}
            </h3>
            <div style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
              <span style={{ fontSize: "0.75rem", color: "var(--color-text-dim)" }}>DPR #{currentRfp.dpr_id}</span>
              <button className="btn btn-outline btn-sm" onClick={() => downloadRfpMd(currentRfp)} title="Download as Markdown">
                <FileText size={14} /> .md
              </button>
              <button className="btn btn-outline btn-sm" onClick={() => downloadRfpPdf(currentRfp, selectedDprObj)} title="Download as PDF">
                <Download size={14} /> PDF
              </button>
            </div>
          </div>
          <div className="markdown-preview">
            <ReactMarkdown>{currentRfp.generated_markdown}</ReactMarkdown>
          </div>
        </div>
      )}

      {!currentRfp && !generating && selectedDpr && (
        <div className="glass-card">
          <div className="empty-state">
            <Wand2 size={40} />
            <p>No RFP generated for this DPR yet. Click "Generate Tender Clauses" to create one.</p>
          </div>
        </div>
      )}

      {!selectedDpr && !loading && (
        <div className="glass-card">
          <div className="empty-state">
            <p>Select an approved DPR above to view or generate its RFP.</p>
          </div>
        </div>
      )}
    </div>
  );
}
